### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kishduke** [zhuyizhou/uscis-tracker#1]
i get an error when running it. no such file or directory: login.yaml

**Comment by fermionian** [comment]
@kishduke  Hi I moved to https://github.com/fermionian/uscisTracker. 
There is an sample login.yaml file there. 
Since I am still building the tracker, so there is not much documentation yet...
Thanks for your interest!

**Comment by kishduke** [comment]
ok so what needs to provided in the yaml file. its asking for user name and password

**Comment by fermionian** [comment]
@kishduke Your uscis account username and password. This tracker needs to login to the website.

**Comment by kishduke** [comment]
Got it thanks

**Comment by kishduke** [comment]
is there a way to run it without logging in. USCIS locks you out after
checking a certain times

**Comment by fermionian** [comment]
@kishduke Even if you don't log in, the website will still lock you after a certain number of queries. It is based on IP. You will be unlocked after 24 hours (or just change IP)
By the way. I will close this issue. Could you move further discussion questions to the new repo?
New repo at : https://github.com/fermionian/uscisTracker

**Comment by zhuyizhou** [comment]
close #1
